"use client";
import { useState } from "react";

const Icon = ({ name, size = 20 }: { name: string; size?: number }) => {
  const paths: Record<string, React.ReactNode> = {
    home: <><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></>, book: <><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v15H6.5A2.5 2.5 0 0 0 4 20.5z"/><path d="M4 5.5v15M8 7h8M8 11h6"/></>, chart: <><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></>, users: <><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2-6 6-6s6 2 6 6M16 4a3 3 0 0 1 0 6M17 14c3.3 0 5 2 5 5"/></>, award: <><circle cx="12" cy="8" r="5"/><path d="m8.5 12-2 9 5.5-3 5.5 3-2-9"/></>, calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>, help: <><circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.5 2.5 0 1 1 3.7 2.2c-1 .6-1.4 1-1.4 2.3M12 17h.01"/></>, search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>, play: <path d="m9 7 8 5-8 5z"/>, download: <><path d="M12 3v12m0 0 5-5m-5 5-5-5"/><path d="M4 18v3h16v-3"/></>, check: <path d="m5 12 4 4L19 6"/>, arrow: <path d="m9 18 6-6-6-6"/>, menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
};

const courses = [
  { title: "Foundations of Clinical Oncology", meta: "12 modules · 18 hours", progress: 68, color: "violet", tag: "Core curriculum" },
  { title: "Radiotherapy Principles", meta: "9 modules · 14 hours", progress: 42, color: "blue", tag: "Radiation oncology" },
  { title: "Oncology Nursing Practice", meta: "15 modules · 22 hours", progress: 24, color: "green", tag: "Nursing pathway" },
];
const nav = [["home", "Overview"], ["book", "My learning"], ["calendar", "Live sessions"], ["chart", "Progress"], ["users", "Community"], ["award", "Certificates"]];

function AcademyView({section,role,notify}:{section:string;role:string;notify:(message:string)=>void}){
  const [answers,setAnswers]=useState<Record<number,string>>({}); const [submitted,setSubmitted]=useState(false); const [uploaded,setUploaded]=useState("");
  if(section==="My learning") return <section className="feature-view"><div className="feature-head"><div><p className="eyebrow">CURRICULUM</p><h2>My learning</h2><p>Structured oncology education with saved progress and assessed competencies.</p></div><span className="status-chip">3 ACTIVE COURSES</span></div><div className="learning-grid">{courses.map((c,i)=><article className="learning-card" key={c.title}><div className={`course-art ${c.color}`}><span>0{i+1}</span><div className="medical-lines"/></div><div><small>{c.tag}</small><h3>{c.title}</h3><p>{c.meta}</p><div className="progress"><i style={{width:`${c.progress}%`}}/></div><b>{c.progress}% complete</b><button onClick={()=>notify(`Opening ${c.title}`)}><Icon name="play"/> Continue course</button></div></article>)}</div><Exam answers={answers} setAnswers={setAnswers} submitted={submitted} setSubmitted={setSubmitted}/></section>;
  if(section==="Live sessions") return <section className="feature-view"><div className="feature-head"><div><p className="eyebrow">FACULTY-LED TEACHING</p><h2>Live sessions</h2><p>Case conferences, lectures and supervised multidisciplinary meetings.</p></div><button className="primary-action" onClick={()=>notify("Calendar invitation downloaded")}>Add all to calendar</button></div><div className="session-table">{[["21 AUG","Multidisciplinary Tumour Board","Prof. Anna Lindberg","14:00 CET"],["25 AUG","Radiotherapy Planning Workshop","Dr. Erik Svensson","16:00 CET"],["02 SEP","Cervical Cancer Masterclass","Prof. Chantal Mukwege","13:00 CET"]].map((s,i)=><article key={s[1]}><strong>{s[0]}</strong><div><h3>{s[1]}</h3><p>{s[2]} · {s[3]}</p></div><span className={i===0?"live-now":""}>{i===0?"REGISTERED":"REGISTER"}</span><button onClick={()=>notify(i===0?"Joining session room":"Registration confirmed")}>{i===0?"Join":"Register"}</button></article>)}</div></section>;
  if(section==="Progress") return <section className="feature-view"><div className="feature-head"><div><p className="eyebrow">PERFORMANCE</p><h2>Progress & competencies</h2><p>Validated learning activity across the oncology training pathway.</p></div><button className="outline-button" onClick={()=>notify("Official transcript prepared")}><Icon name="download"/> Export transcript</button></div><div className="progress-summary"><article><strong>36%</strong><span>Program completion</span></article><article><strong>86%</strong><span>Assessment average</span></article><article><strong>47.5 h</strong><span>Verified learning</span></article><article><strong>8/10</strong><span>Competencies passed</span></article></div><div className="competencies"><h3>Clinical competency record</h3>{[["Oncological history and examination",100],["Treatment decision-making",78],["Radiotherapy planning",55],["Systemic treatment safety",42]].map(c=><div key={String(c[0])}><span>{c[0]}</span><div className="progress"><i style={{width:`${c[1]}%`}}/></div><b>{c[1]}%</b></div>)}</div></section>;
  if(section==="Community") return <section className="feature-view"><div className="feature-head"><div><p className="eyebrow">ACADEMY NETWORK</p><h2>Community</h2><p>Connect with learners and Scandinavian faculty across the program.</p></div><button className="primary-action" onClick={()=>notify("New discussion window opened")}>Start discussion</button></div><div className="discussion-list">{[["AL","Prof. Anna Lindberg","How do you approach organ-at-risk prioritisation in re-irradiation?","12 replies"],["JM","Dr. Jean Mbala","Shared: Cervical cancer staging clinical reference","8 replies"],["SK","Nurse Sara Karlsson","Managing acute toxicity: practical nursing checklist","21 replies"]].map(d=><article key={d[2]}><div className="avatar">{d[0]}</div><div><strong>{d[1]}</strong><p>{d[2]}</p><small>{d[3]} · Today</small></div><button onClick={()=>notify("Discussion opened")}><Icon name="arrow"/></button></article>)}</div></section>;
  if(section==="Certificates") return <section className="feature-view"><div className="feature-head"><div><p className="eyebrow">VERIFIED ACHIEVEMENTS</p><h2>Certificates</h2><p>Secure credentials become available after all required assessments are passed.</p></div></div><div className="certificate-card"><div className="certificate-seal">D</div><div><span>COURSE CERTIFICATE</span><h3>Foundations of Clinical Oncology</h3><p>Issued by Durckheim Oncology Academy · Scandinavian faculty verified</p></div><button onClick={()=>notify("Certificate PDF downloaded")}><Icon name="download"/> Download</button></div></section>;
  if(role!=="Learner") return <Management role={role} notify={notify} uploaded={uploaded} setUploaded={setUploaded}/>;
  return null;
}

function Exam({answers,setAnswers,submitted,setSubmitted}:{answers:Record<number,string>;setAnswers:(v:Record<number,string>)=>void;submitted:boolean;setSubmitted:(v:boolean)=>void}){const qs=[{q:"Which principle best describes fractionation in radiotherapy?",a:["Dose delivery in multiple smaller treatments","One maximum dose for every tumour","Treatment without imaging"],correct:"Dose delivery in multiple smaller treatments"},{q:"What is the principal purpose of an MDT?",a:["Administrative billing","Coordinated multidisciplinary treatment decisions","Replacing informed consent"],correct:"Coordinated multidisciplinary treatment decisions"}];const score=qs.filter((q,i)=>answers[i]===q.correct).length;return <section className="exam-card"><p className="eyebrow">KNOWLEDGE CHECK</p><h3>Module assessment</h3>{qs.map((q,i)=><fieldset key={q.q}><legend>{i+1}. {q.q}</legend>{q.a.map(a=><label key={a}><input type="radio" name={`q${i}`} checked={answers[i]===a} onChange={()=>setAnswers({...answers,[i]:a})}/>{a}</label>)}</fieldset>)}{submitted?<div className={score===2?"exam-result pass":"exam-result"}>{score===2?"Passed — 100%":"Review required — 50%"}</div>:<button className="primary-action" disabled={Object.keys(answers).length<2} onClick={()=>setSubmitted(true)}>Submit assessment</button>}</section>}

function Management({role,notify,uploaded,setUploaded}:{role:string;notify:(m:string)=>void;uploaded:string;setUploaded:(s:string)=>void}){return <section className="feature-view"><div className="feature-head"><div><p className="eyebrow">{role.toUpperCase()} WORKSPACE</p><h2>{role} dashboard</h2><p>{role==="Professor"?"Create teaching, examinations and review learner submissions.":role==="Government"?"Monitor aggregated national training outcomes without access to private learner records.":"Manage users, roles, curriculum and academy operations."}</p></div></div><div className="management-grid"><article><h3>{role==="Professor"?"Upload teaching material":"Learner administration"}</h3>{role==="Professor"?<><label className="upload-zone"><input type="file" accept="video/*,.pdf" onChange={e=>setUploaded(e.target.files?.[0]?.name||"")}/><Icon name="book"/><strong>{uploaded||"Choose video or PDF"}</strong><span>Files are reviewed before publication</span></label>{uploaded&&<button className="primary-action" onClick={()=>notify(`${uploaded} queued for publication`)}>Publish material</button>}</>:<><div className="admin-stat"><strong>1,248</strong><span>Active learners</span></div><div className="admin-stat"><strong>38</strong><span>Faculty accounts</span></div><button className="primary-action" onClick={()=>notify("New user form opened")}>Add user</button></>}</article><article><h3>Program health</h3><div className="metric-row"><span>Active this month</span><b>91%</b></div><div className="metric-row"><span>Assessment completion</span><b>84%</b></div><div className="metric-row"><span>Certificate eligibility</span><b>72%</b></div><button className="outline-button" onClick={()=>notify("Detailed report prepared")}><Icon name="download"/> Download report</button></article></div></section>}

export default function Home() {
  const [active, setActive] = useState("Overview"); const [menu, setMenu] = useState(false); const [role, setRole] = useState(() => { if (typeof window === "undefined") return "Learner"; const requested = new URLSearchParams(window.location.search).get("role"); return ["Learner","Professor","Government","Administrator"].includes(requested || "") ? requested! : "Learner"; }); const [canManageRoles] = useState(() => typeof window !== "undefined" && new URLSearchParams(window.location.search).get("role") === "Administrator"); const [notice, setNotice] = useState("");
  const notify = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };
  return <main className="academy-shell">
    <aside className={`sidebar ${menu ? "open" : ""}`}>
      <div className="brand"><div className="brand-logo"><img src="/durckheim-logo.png" alt="Durckheim AB" /></div><div><strong>DURCKHEIM</strong><span>ONCOLOGY ACADEMY</span></div><button className="mobile-close" onClick={() => setMenu(false)} aria-label="Close navigation"><Icon name="close" /></button></div>
      <div className="profile-block"><div className="avatar">DB</div><div><strong>Dr. Durckheim Blessing</strong><span>{role} · Cohort 2026</span></div></div>
      <nav aria-label="Main navigation"><p className="nav-label">ACADEMY</p>{nav.map(([icon, label]) => <button key={label} className={active === label ? "active" : ""} onClick={() => { setActive(label); setMenu(false); }}><Icon name={icon}/><span>{label}</span>{label === "Live sessions" && <b>3</b>}</button>)}<p className="nav-label lower">SUPPORT</p><button onClick={() => notify("Support centre opened")}><Icon name="help"/><span>Help centre</span></button></nav>
      <div className="sidebar-card"><span>PROGRAM PROGRESS</span><strong>Year 1 of 5</strong><div className="progress"><i style={{width:"36%"}}/></div><small>36% completed</small></div>
      <div className="legal">© 2026 Durckheim AB<br/>Scandinavian quality in oncology</div>
    </aside>
    <section className="workspace">
      <header className="topbar"><button className="menu-button" onClick={() => setMenu(true)} aria-label="Open navigation"><Icon name="menu"/></button><div className="search"><Icon name="search"/><input aria-label="Search academy" placeholder="Search courses, lessons and resources…"/></div><div className="top-actions">{canManageRoles?<select value={role} onChange={e=>{setRole(e.target.value);notify(`Administrator preview: ${e.target.value}`);}} aria-label="Administrator role management"><option>Learner</option><option>Professor</option><option>Government</option><option>Administrator</option></select>:<span className="locked-role"><Icon name="check" size={15}/>{role}</span>}<button className="icon-button" aria-label="Notifications"><Icon name="bell"/><i>3</i></button><button className="language">EN <span>⌄</span></button></div></header>
      <div className="content">
        {(active!=="Overview"||role!=="Learner")&&<AcademyView section={active} role={role} notify={notify}/>} 
        {active==="Overview"&&role==="Learner"&&<>
        <div className="welcome-row"><div><p className="eyebrow">THURSDAY, 20 AUGUST 2026</p><h1>Welcome back, Durckheim.</h1><p>Continue building the expertise that transforms cancer care.</p></div><button className="outline-button" onClick={()=>notify("Weekly progress report prepared")}><Icon name="download"/> Download report</button></div>
        <section className="hero-card"><div className="hero-copy"><span className="live-pill"><i/> CONTINUE LEARNING</span><h2>Radiotherapy Principles</h2><p>Module 4 · Treatment planning and dose prescription</p><div className="lesson-progress"><div><span>Course progress</span><b>42%</b></div><div className="progress"><i style={{width:"42%"}}/></div></div><button onClick={()=>notify("Opening Module 4: Treatment planning")}><Icon name="play" size={18}/> Resume lesson</button></div><div className="hero-visual" aria-hidden="true"><div className="orb one"/><div className="orb two"/><div className="cross"><span/><span/></div><p>4<span>/ 9</span></p><small>MODULES</small></div></section>
        <section className="stats-grid"><article><div className="stat-icon purple"><Icon name="book"/></div><div><span>Courses in progress</span><strong>3</strong><small>2 due this month</small></div></article><article><div className="stat-icon teal"><Icon name="chart"/></div><div><span>Learning hours</span><strong>47.5</strong><small>+6.5 this week</small></div></article><article><div className="stat-icon gold"><Icon name="award"/></div><div><span>Assessments passed</span><strong>8</strong><small>Average score 86%</small></div></article><article><div className="stat-icon blue"><Icon name="calendar"/></div><div><span>Live sessions</span><strong>3</strong><small>Next: tomorrow, 14:00</small></div></article></section>
        <div className="main-grid"><section className="panel course-panel"><div className="panel-heading"><div><p className="eyebrow">YOUR CURRICULUM</p><h3>Continue learning</h3></div><button onClick={()=>setActive("My learning")}>View all <Icon name="arrow" size={16}/></button></div><div className="course-list">{courses.map((course,index)=><article key={course.title}><div className={`course-art ${course.color}`}><span>0{index+1}</span><div className="medical-lines"/></div><div className="course-info"><span>{course.tag}</span><h4>{course.title}</h4><p>{course.meta}</p><div className="course-progress"><div className="progress"><i style={{width:`${course.progress}%`}}/></div><b>{course.progress}%</b></div></div><button className="round-button" aria-label={`Open ${course.title}`} onClick={()=>notify(`Opening ${course.title}`)}><Icon name="arrow"/></button></article>)}</div></section>
          <aside className="side-column"><section className="panel next-session"><div className="panel-heading"><div><p className="eyebrow">UP NEXT</p><h3>Live session</h3></div><span className="live-tag">LIVE</span></div><div className="session-date"><strong>21</strong><span>AUG<br/>FRIDAY</span></div><h4>Multidisciplinary Tumour Board</h4><p>Head & neck cancer: complex cases</p><div className="host"><div>AL</div><span><strong>Prof. Anna Lindberg</strong><small>Karolinska University Hospital</small></span></div><div className="time-row"><span>14:00–15:30 CET</span><span>90 min</span></div><button onClick={()=>notify("You are registered for the live session")}>Join session</button></section>
          <section className="panel resources"><div className="panel-heading"><div><p className="eyebrow">RESOURCE LIBRARY</p><h3>PDF downloads</h3></div></div><a href="/api/resources/radiotherapy-guide" download><span className="pdf-icon">PDF</span><div><strong>Radiotherapy Quick Guide</strong><small>Clinical reference · PDF</small></div><Icon name="download"/></a><a href="/api/resources/oncology-logbook" download><span className="pdf-icon">PDF</span><div><strong>Clinical Oncology Logbook</strong><small>Portfolio template · PDF</small></div><Icon name="download"/></a><a href="/api/resources/nursing-handbook" download><span className="pdf-icon">PDF</span><div><strong>Oncology Nursing Handbook</strong><small>Practice guide · PDF</small></div><Icon name="download"/></a></section></aside>
        </div></>}
      </div>
    </section>
    {menu&&<button className="overlay" onClick={()=>setMenu(false)} aria-label="Close menu"/>}{notice&&<div className="toast"><Icon name="check"/>{notice}</div>}
  </main>;
}
